security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_API:         ROLE_USER
        ROLE_ADMIN:       ROLE_API
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_dashboard:
            pattern: ^/admin
            anonymous: true
            form_login:
                login_path: admin_login
                check_path: admin_login
                username_parameter: _email
                default_target_path: admin_dashboard
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: admin_logout
                target: admin_login

        api_login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:         api_login
                username_path:      email
                password_path:      password
                success_handler:    lexik_jwt_authentication.handler.authentication_success
                failure_handler:    lexik_jwt_authentication.handler.authentication_failure

        api_refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true

        api_auth:
            pattern: ^/api/auth
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
#            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: true


    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, role: ROLE_ADMIN }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

#        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_API }
